services:

  mysqldb:
    image: mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQL_DOCKER_PORT

  app:
    build: .
    depends_on:
      - mysqldb
    links:
    - mysqldb
    ports:
    - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT